### ISSUE TITLE
Could not retrieve configuration: 'InputText' object has no attribute 'model_dump'

### ISSUE THREAD

**Issue by shyamshyre** [weaviate/Verba#154]
## Description
Post following instruction ran into following issue, where the ui just ends up with loading icon.

## Is this a bug or a feature?
- [x] Bug
- [ ] Feature

## Steps to Reproduce
post running below steps ran into following steps

pip install goldenverba

git clone https://github.com/weaviate/Verba

pip install -e .

verba start

**Comment by thomashacker** [comment]
This might be an issue with pydantic, which pydantic version do you have currently installed? And what python version are you using? 

This might be related: https://stackoverflow.com/questions/77251901/pydantic-basemodel-model-dump-throughs-attributeerror

**Comment by wilmeragsgh** [comment]
I had this issue, my workaround was to create a fresh conda environment:

```
conda create -n venv
conda activate venv
pip install goldenverba
verba start
```

It worked with `pydantic=2.7.1` which seems to be related to: 

> This might be an issue with pydantic, which pydantic version do you have currently installed? And what python version are you using?
> 
> This might be related: https://stackoverflow.com/questions/77251901/pydantic-basemodel-model-dump-throughs-attributeerror
