### ISSUE TITLE
websocket error

### ISSUE THREAD

**Issue by fils** [weaviate/Verba#38]
Same error in both main and dev branches

Python 3.10.12 on Fedora Linux 38

tried re-installing websocket and websocket-client but no resolution.

Note, this is working on my Ubuntu machine with python 3.11.4, so not sure if that is an issue or not.  Both are above the recommend 3.9 level.

 I appreciate the fact it is working on one machine and not the other points to it being on my end.  However, wanted to post the issue in case someone could help me with it, or it was of broader interest. 

```bash
✔ Received query: what is ocean infohub
ℹ Retrieved Context of 1158 tokens
✔ Succesfully processed query: what is ocean infohub
INFO:     192.168.202.109:42404 - "POST /api/query HTTP/1.1" 200 OK
✘ WebSocket Error: type object 'GeneratePayload' has no attribute
'model_validate_json'
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/fils/src/git/Verba/goldenverba/server/api.py", line 581, in websocket_generate_stream
    payload = GeneratePayload.model_validate_json(data)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'GeneratePayload' has no attribute 'model_validate_json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/fils/.local/lib/python3.11/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 254, in run_asgi
    result = await self.app(self.scope, self.asgi_receive, self.asgi_send)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fils/.local/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fils/.local/lib/python3.11/site-packages/fastapi/applications.py", line 1106, in __call__
    await super().__call__(scope, receive, send)
  File "/home/fils/.local/lib/python3.11/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/fils/.local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 149, in __call__
    await self.app(scope, receive, send)
  File "/home/fils/.local/lib/python3.11/site-packages/starlette/middleware/cors.py", line 75, in __call__
    await self.app(scope, receive, send)
  File "/home/fils/.local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/home/fils/.local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/home/fils/.local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/home/fils/.local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/home/fils/.local/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/home/fils/.local/lib/python3.11/site-packages/starlette/routing.py", line 341, in handle
    await self.app(scope, receive, send)
  File "/home/fils/.local/lib/python3.11/site-packages/starlette/routing.py", line 82, in app
    await func(session)
  File "/home/fils/.local/lib/python3.11/site-packages/fastapi/routing.py", line 325, in app
    await dependant.call(**values)
  File "/home/fils/src/git/Verba/goldenverba/server/api.py", line 598, in websocket_generate_stream
    await websocket.send_json(
  File "/home/fils/.local/lib/python3.11/site-packages/starlette/websockets.py", line 171, in send_json
    text = json.dumps(data, separators=(",", ":"))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/usr/lib64/python3.11/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type AttributeError is not JSON serializable
ERROR:    closing handshake failed
Traceback (most recent call last):
  File "/home/fils/.local/lib/python3.11/site-packages/websockets/legacy/server.py", line 248, in handler
    await self.close()
  File "/home/fils/.local/lib/python3.11/site-packages/websockets/legacy/protocol.py", line 766, in close
    await self.write_close_frame(Close(code, reason))
  File "/home/fils/.local/lib/python3.11/site-packages/websockets/legacy/protocol.py", line 1232, in write_close_frame
    await self.write_frame(True, OP_CLOSE, data, _state=State.CLOSING)
  File "/home/fils/.local/lib/python3.11/site-packages/websockets/legacy/protocol.py", line 1205, in write_frame
    await self.drain()
  File "/home/fils/.local/lib/python3.11/site-packages/websockets/legacy/protocol.py", line 1194, in drain
    await self.ensure_open()
  File "/home/fils/.local/lib/python3.11/site-packages/websockets/legacy/protocol.py", line 935, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: sent 1000 (OK); no close frame received
INFO:     connection closed
INFO:     192.168.202.109:51200 - "GET /api/health HTTP/1.1" 200 OK
ℹ Document ID received: 8a66ba1a-5b25-4c74-83f0-d30c7b7affb0
```

**Comment by fils** [comment]
so rather than using my conda env, I used the RTFM recommended ```python3 -m virtualenv venv```

and it works fine..   sorry for the un-necessary chatter..
